SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS ANSWER_TABLE;
DROP TABLE IF EXISTS QUIZ_MANAGE;
DROP TABLE IF EXISTS QUIZ_TABLE;
DROP TABLE IF EXISTS GENRE_TABLE;
DROP TABLE IF EXISTS id_sequence;
DROP TABLE IF EXISTS now_point;
DROP TABLE IF EXISTS POINT_TABLE;
DROP TABLE IF EXISTS QUIZ_NUMBER;
DROP TABLE IF EXISTS TEAM_TABLE;




/* Create Tables */

CREATE TABLE ANSWER_TABLE
(
	ID int NOT NULL,
	QUIZ_NUMBER int NOT NULL,
	TEAM_ID int NOT NULL,
	ANSWER char(255),
	NOW_POINT int,
	CORRECT_FLAG int COMMENT '正解が0
不正解が1',
	QUESTION_ID int NOT NULL,
	PRIMARY KEY (ID, QUIZ_NUMBER, TEAM_ID)
);


CREATE TABLE GENRE_TABLE
(
	GENRE_ID int NOT NULL,
	GENRE_NAME char(100),
	PRIMARY KEY (GENRE_ID)
);


CREATE TABLE id_sequence
(
	game_id int NOT NULL,
	PRIMARY KEY (game_id)
);


CREATE TABLE now_point
(
	id int NOT NULL,
	team_number int NOT NULL,
	now_point int DEFAULT 0,
	PRIMARY KEY (id, team_number)
);


CREATE TABLE POINT_TABLE
(
	POINT_ID int NOT NULL,
	POINT int,
	PRIMARY KEY (POINT_ID)
);


CREATE TABLE QUIZ_MANAGE
(
	ID int NOT NULL,
	QUIZ_NUMBER int NOT NULL,
	CORRECT_TEAM_ID_1 int,
	CORRECT_TEAM_ID_2 int,
	CORRECT_TEAM_ID_3 int,
	CORRECT_TEAM_ID_4 int,
	CORRECT_TEAM_ID_5 int,
	LOSER_ID int COMMENT '逆転クイズの敗者',
	QUESTION_ID int NOT NULL,
	PRIMARY KEY (ID, QUIZ_NUMBER)
);


CREATE TABLE QUIZ_NUMBER
(
	ID int NOT NULL COMMENT '大会の識別番号',
	QUIZ_NUMBER int NOT NULL COMMENT '現在の問題数',
	PRIMARY KEY (ID)
);


CREATE TABLE QUIZ_TABLE
(
	ID int NOT NULL,
	QUESTION_ID int NOT NULL,
	GENRE_ID int NOT NULL,
	POINT_ID int NOT NULL,
	QUESTION_NUMBER int,
	REMAIN_QUESTION_NUMBER int COMMENT '残りの問題数',
	PRIMARY KEY (ID, QUESTION_ID)
);


CREATE TABLE TEAM_TABLE
(
	TEAM_ID int NOT NULL,
	TEAM_NAME char(100),
	PRIMARY KEY (TEAM_ID)
);



/* Create Foreign Keys */

ALTER TABLE QUIZ_TABLE
	ADD FOREIGN KEY (GENRE_ID)
	REFERENCES GENRE_TABLE (GENRE_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE QUIZ_TABLE
	ADD FOREIGN KEY (POINT_ID)
	REFERENCES POINT_TABLE (POINT_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ANSWER_TABLE
	ADD FOREIGN KEY (ID, QUESTION_ID)
	REFERENCES QUIZ_TABLE (ID, QUESTION_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE QUIZ_MANAGE
	ADD FOREIGN KEY (ID, QUESTION_ID)
	REFERENCES QUIZ_TABLE (ID, QUESTION_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE now_point
	ADD FOREIGN KEY (team_number)
	REFERENCES TEAM_TABLE (TEAM_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE QUIZ_MANAGE
	ADD FOREIGN KEY (CORRECT_TEAM_ID_2)
	REFERENCES TEAM_TABLE (TEAM_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE QUIZ_MANAGE
	ADD FOREIGN KEY (CORRECT_TEAM_ID_4)
	REFERENCES TEAM_TABLE (TEAM_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE QUIZ_MANAGE
	ADD FOREIGN KEY (CORRECT_TEAM_ID_5)
	REFERENCES TEAM_TABLE (TEAM_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE QUIZ_MANAGE
	ADD FOREIGN KEY (LOSER_ID)
	REFERENCES TEAM_TABLE (TEAM_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE QUIZ_MANAGE
	ADD FOREIGN KEY (CORRECT_TEAM_ID_1)
	REFERENCES TEAM_TABLE (TEAM_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE QUIZ_MANAGE
	ADD FOREIGN KEY (CORRECT_TEAM_ID_3)
	REFERENCES TEAM_TABLE (TEAM_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


INSERT INTO myfirstdatabase.genre_table ( GENRE_ID, GENRE_NAME ) VALUES (1,'国語');
INSERT INTO myfirstdatabase.genre_table ( GENRE_ID, GENRE_NAME ) VALUES (2,'数学');
INSERT INTO myfirstdatabase.genre_table ( GENRE_ID, GENRE_NAME ) VALUES (3,'理科');
INSERT INTO myfirstdatabase.genre_table ( GENRE_ID, GENRE_NAME ) VALUES (4,'社会');
INSERT INTO myfirstdatabase.genre_table ( GENRE_ID, GENRE_NAME ) VALUES (5,'英語');
INSERT INTO myfirstdatabase.genre_table ( GENRE_ID, GENRE_NAME ) VALUES (6,'芸能');
INSERT INTO myfirstdatabase.genre_table ( GENRE_ID, GENRE_NAME ) VALUES (7,'映画');
INSERT INTO myfirstdatabase.genre_table ( GENRE_ID, GENRE_NAME ) VALUES (8,'漫画・アニメ');
INSERT INTO myfirstdatabase.genre_table ( GENRE_ID, GENRE_NAME ) VALUES (9,'ゲーム');
INSERT INTO genre_table VALUES ( 10,'俺' );
INSERT INTO genre_table VALUES ( 11,'その他' );


INSERT INTO myfirstdatabase.point_table ( POINT_ID, POINT ) VALUES (1,10);
INSERT INTO myfirstdatabase.point_table ( POINT_ID, POINT ) VALUES (2,20);
INSERT INTO myfirstdatabase.point_table ( POINT_ID, POINT ) VALUES (3,30);
INSERT INTO myfirstdatabase.point_table ( POINT_ID, POINT ) VALUES (4,100);


INSERT INTO myfirstdatabase.team_table ( TEAM_ID, TEAM_NAME ) VALUES (1,'チームさと');
INSERT INTO myfirstdatabase.team_table ( TEAM_ID, TEAM_NAME ) VALUES (2,'チームさわ');
INSERT INTO myfirstdatabase.team_table ( TEAM_ID, TEAM_NAME ) VALUES (3,'チームじいちゃん');
INSERT INTO myfirstdatabase.team_table ( TEAM_ID, TEAM_NAME ) VALUES (4,'チームけーた');
INSERT INTO myfirstdatabase.team_table ( TEAM_ID, TEAM_NAME ) VALUES (5,'チームにーに');

INSERT INTO myfirstdatabase.id_sequence ( game_id ) VALUES (0);

commit;